# Generated by Django 3.1.5 on 2021-01-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='displayedAddress',
            field=models.TextField(default='Warszawa, Brzeska 11'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='quickstart.library'),
        ),
    ]
